# action.yml
name: 'Kicad pipeline'
description: 'validate schematic'
inputs:
  kicad-project-path:
    description: 'Path to kicad project'
    required: true
  kicad-schematic-filename:
    description: 'filename of kicad schematic'
    required: true
  kicad-board-filename:
    description: 'filename of .kicad_pcb file'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kicad-project-path }}
    - ${{ inputs.kicad-schematic-filename }}
    - ${{ inputs.kicad-board-filename }}


